version: 2.1

jobs:
  # Job Uno
  print_myVar:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Showing my Variable"
          command: echo ${MY_USERNAME}
  
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello world" > output.txt 
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - print_myVar
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
