version: 2.1

jobs:
  # Job Uno
  print_myVar:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Showing my Variable"
          command: echo ${MY_USERNAME}

workflows:
  say-hello-workflow:
    jobs:
      - print_myVar
