version: 2.1

jobs:
  # Job Uno
  print_hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Running a stanky command"
          command: echo "** Eat your veggies ** "
  # Job Dos
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run the playbook"
          command: echo "Ansible is supposed to run here now OK!, Eh OK"
  print_world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Hey I am Groot"
          command: echo "DEEZ NUTs"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - say-hello
      - print_world
